apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: api-gateway-cert-sap
  namespace: litellm
  labels:
    app: api-gateway
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/component: tls
    app.kubernetes.io/part-of: serverless-agentic-platform
    managed-by: gke-ingress
spec:
  domains:
    - api.serverless-agentic-platform.com
