apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: sagc-iap-config
  namespace: litellm
spec:
  iap:
    enabled: true
    oauthclientCredentials:
      secretName: iap-oauth-credentials # This secret holds the OAuth client ID/Secret
