apiVersion: v1
kind: ServiceAccount
metadata:
  name: litellm-ksa
spec:
  template:
    spec:
      containers: []
  jobTemplate:
    spec:
      template:
        spec:
          containers: []
  containers: []
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway-sa
spec:
  template:
    spec:
      containers: []
  jobTemplate:
    spec:
      template:
        spec:
          containers: []
  containers: []
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: litellm-sa
spec:
  template:
    spec:
      containers: []
  jobTemplate:
    spec:
      template:
        spec:
          containers: []
  containers: []
