apiVersion: v1
kind: ServiceAccount
metadata:
  name: litellm-ksa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway-sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: litellm-sa
