apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/backend-config: '{"default": "api-gateway-backend-config"}'
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/neg-status: '{"network_endpoint_groups":{"80":"k8s1-42c836c7-agentic-api-gateway-service-80-cf4be768"},"zones":["us-central1-a","us-central1-f"]}'
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"cloud.google.com/backend-config":"{\"default\": \"api-gateway-backend-config\"}"},"name":"api-gateway-service","namespace":"agentic"},"spec":{"ports":[{"name":"http","port":80,"protocol":"TCP","targetPort":8080}],"selector":{"app":"api-gateway"},"type":"NodePort"}}
  name: api-gateway-service
  namespace: agentic
spec:
  - 10.20.7.8
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: api-gateway
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
