apiVersion: v1
kind: Namespace
metadata:
  name: litellm
  labels:
    app: litellm
    environment: dev
spec:
  template:
    spec:
      containers: []
  jobTemplate:
    spec:
      template:
        spec:
          containers: []
  containers: []
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: litellm-sa
  namespace: litellm
  annotations:
    iam.gke.io/gcp-service-account: litellm-wif-sa@alert-hall-466720-c0.iam.gserviceaccount.com
spec:
  template:
    spec:
      containers: []
  jobTemplate:
    spec:
      template:
        spec:
          containers: []
  containers: []
