apiVersion: apps/v1
kind: Deployment
metadata:
  name: litellm-gateway
  namespace: litellm
  labels:
    cost-center: research-dev
  annotations:
    iam.gke.io/gcp-service-account: litellm-sa@alert-hall-466720-c0.iam.gserviceaccount.com
    iam.gcp.io/gcp-service-account: litellm-sa@alert-hall-466720-c0.iam.gserviceaccount.com
spec:
  selector:
    matchLabels:
      app: litellm-gateway
  template:
    metadata:
      labels:
        app: litellm-gateway
        cost-center: research-dev
      annotations:
        iam.gke.io/gcp-service-account: litellm-sa@alert-hall-466720-c0.iam.gserviceaccount.com
        iam.gcp.io/gcp-service-account: litellm-sa@alert-hall-466720-c0.iam.gserviceaccount.com
    spec:
      serviceAccountName: litellm-sa
      containers:
      - name: litellm
        image: docker.io/litellm/litellm:v1.84.0
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
