apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp-secret-store
  namespace: litellm
spec:
  provider:
    gcpsm:
      projectID: alert-hall-466720-c0
      auth:
        workloadIdentity:
          serviceAccountRef:
            name: litellm-sa
